# Generated by Django 3.2 on 2021-06-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_slidermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/slider/'),
        ),
    ]
